version: "3.9"
services:
  mongo:
    container_name: calendar-mongo
    restart: always
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  server:
    container_name: calendar-server-node
    restart: always
    build: 
      context: ./server
      dockerfile: server.Dockerfile
    ports: 
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_CONNECTION: "mongodb://mongo:27017/calendar-mongo?authSource=admin"
      URL_APP: http://localhost:8080
    depends_on: 
      - "mongo"
  client:
    container_name: calendar-client-vue
    restart: always
    build:
      context: ./client
      dockerfile: client.Dockerfile
    ports:
      - "8080:8080"
    environment:
      VUE_APP_URL: http://localhost:3000/
    depends_on: 
      - "server"
volumes:
  mongodb: